//AUTOGENERATED FILE FROM png2asset
// Conversion args: ur_tile_token_p1.png -noflip -no_palettes -tiles_only

#ifndef METASPRITE_ur_tile_token_p1_H
#define METASPRITE_ur_tile_token_p1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ur_tile_token_p1_TILE_ORIGIN 0
#define ur_tile_token_p1_TILE_W 8
#define ur_tile_token_p1_TILE_H 16
#define ur_tile_token_p1_WIDTH 16
#define ur_tile_token_p1_HEIGHT 16
#define ur_tile_token_p1_TILE_COUNT 4

BANKREF_EXTERN(ur_tile_token_p1)

extern const uint8_t ur_tile_token_p1_tiles[64];

#endif
